### PR TITLE
fix: resolve mypyc compilation errors

### LINKED ISSUE #72: Build from source fails: mypyc type error in packets.py (bytearray vs bytes)
## Description

Building `mysql-mimic==3.0.2` from source (without a pre-built wheel) fails because mypyc's mypy type-checking rejects a `bytearray` argument where `bytes` is expected.

This affects any platform/Python combination where a pre-built wheel is not available (e.g. Windows, since wheel builds were dropped in 48a7b3d).

## Build error

```
Building mysql-mimic==3.0.2
x Failed to build `mysql-mimic==3.0.2`
|- The build backend returned an error
\- Call to `setuptools.build_meta.build_wheel` failed (exit code: 1)

    [stdout]
    3.0.2
    mysql_mimic/packets.py:589: error: Argument 1 to "decode" of
    "CharacterSet" has incompatible type "bytearray"; expected "bytes"
    [arg-type]
```

## Root cause

In `packets.py`, the `_read_params` function has:

```python
def _read_params(
    capabilities: Capabilities,
    client_charset: CharacterSet,
    reader: io.BytesIO,
    parameter_count: int,
    buffers: Optional[Dict[int, bytearray]] = None,
) -> Sequence[Tuple[Optional[str], Any]]:
```

And later:

```python
params.append((param_name, client_charset.decode(buffers[i])))
```

`CharacterSet.decode` is typed as:

```python
def decode(self, b: bytes) -> str:
    return b.decode(self.codec)
```

`buffers[i]` is a `bytearray`, but `decode()` expects `bytes`. While `bytearray` is compatible at runtime, mypy (and therefore mypyc) rejects this as a type error under strict mode.

Since PR #71 added mypyc compilation of `packets.py`, and mypyc runs mypy as part of the build, this type error now causes the entire `build_wheel` to fail.

## Suggested fix

Either:

1. Change the `decode` signature to accept `Union[bytes, bytearray]` (or `bytes | bytearray`):
   ```python
   def decode(self, b: bytes | bytearray) -> str:
       return b.decode(self.codec)
   ```

2. Or cast at the call site:
   ```python
   params.append((param_name, client_charset.decode(bytes(buffers[i]))))
   ```

## Workaround

Setting `NO_MYPYC=1` before building skips mypyc compilation and allows the package to install as pure Python:

```
NO_MYPYC=1 pip install mysql-mimic==3.0.2
```

## Environment

- Python 3.13.9
- OS: Windows 11 Pro
- pip/uv source build (no pre-built wheel available for Windows)
- mysql-mimic 3.0.2 (also affects 3.0.0 and 3.0.1)

### PR DESCRIPTION
**Pull request by shauneccles**
## Summary

Fixes two mypyc compilation errors that were silently swallowed by `except Exception` in setup.py, and removes the `NO_MYPYC` workaround from CI (introduced in #75).

- **charset.py**: Widen `CharacterSet.decode()` type from `bytes` to `bytes | bytearray` — `packets.py:589` passes `bytearray` buffers which fails mypyc's strict type checking
- **results.py**: Replace `bytearray` with `List[int]` in `NullBitmap` — mypyc does not support `bytearray` as a native type (`ValueError: bytearray is not a valid sequence`). `List[int]` preserves the same indexing and mutation semantics.
- **tests.yml**: Remove `NO_MYPYC=1` from all CI jobs now that compilation passes cleanly. The lint job validates mypyc compilation on every PR.

Fixes #72. Supersedes #73.

## Depends on

#75 (CI modernization) — should be merged first.

## Test plan

- [x] `python test_mypyc.py` compiles all 6 extensions successfully
- [x] 439 tests pass locally
- [x] CI fully green (lint with mypyc validation, all test matrix entries, integration)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by shauneccles** [comment]
Superseded by a single comprehensive PR covering mypyc fixes, CI modernization, and multiplatform wheel builds with mypyc validation.
